#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in pkill mount umount pacman updatedb make su shutdown poweroff ; do
	alias $command="doas $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	yt="yt-dlp --downloader aria2c --downloader-args '-x 16 -s 16' --add-metadata -i" \
	yta="yt-dlp -x --audio-quality 0 --audio-format flac --embed-thumbnail --embed-metadata" \
	ffmpeg="ffmpeg -hide_banner" \
  cat="bat" \

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
alias \
  piprm="pip-autoremove" \
	ka="killall" \
  mov="mov-cli" \
	g="git" \
  gap="git add . ;git commit -m 'auto-commit'; git push" \
	trm="transmission-remote" \
	sdn="shutdown -h now" \
	v="$EDITOR" \
	p="pacman" \
	z="zathura" \
	l="ls -al" \
	aur="baph -n" \
	sv="doas systemctl" \
	bdi="btds --d-modules ~/.config/discord/0.0.21/modules/ install" \
	pip="python -m pip" \
	py="python" \
  aria="aria2c -s 16 -x 16" \
  wiki="nvim -c VimwikiIndex" \
  diary="nvim -c VimwikiDiaryIndex" \

alias \
  dot="/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME" \
	pkf="pkgfile" \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
