#!/bin/sh

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!
setbg ~/pics/wal/ &
remaps &
redshift -l 28.644800:77.216721 &
unclutter --timeout 2 &
picom &
sxhkd &
pipewire-pulse &
checkup &
dunst &

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"

exec startdwm
# dunst &
