#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
screen &		# Sets up the display(s)
redshift -l 28.644800:77.216721 &
unclutter --timeout 2 &
remaps &		# run the remaps script, switching caps/esc and more; check it for more infoj
setbg

autostart="clipmenud picom dunst pipewire-pulse checkup"

for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
