#!/bin/sh

# Get the volume level and convert it to a percentage
volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
volume=$(echo "$volume" | awk '{print $2}')
volume=$(echo "( $volume * 100 ) / 1" | bc)

fyi -t 1000 -r 99 -a 'wp-vol' -H int:value:$volume "Volume: ${volume}%"
