#!/bin/bash

while true; do
  price=$(curl -s 'https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd' | jq -r '.bitcoin.usd')
  if [ -n "$price" ]; then
    echo "{\"text\": \"BTC: \$${price}\"}"
  else
    echo "{\"text\": \"BTC: Price unavailable\"}"
  fi
  sleep 5
done

