# Main background
theme[main_bg]="#1b2b32"

# Main text color
theme[main_fg]="#fae6c1"

# Title color for boxes
theme[title]="#fae6c1"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#2e4651"

# Background color of selected items
theme[selected_bg]="#8d786f"

# Foreground color of selected items
theme[selected_fg]="#344852"

# Color of inactive/disabled text
theme[inactive_fg]="#1b2b32"

# Color of text appearing on top of graphs
theme[graph_text]="#fae6c1"

# Misc colors for processes box
theme[proc_misc]="#2e4651"

# CPU box outline color
theme[cpu_box]="#8d786f"

# Memory/disks box outline color
theme[mem_box]="#8d786f"

# Network up/down box outline color
theme[net_box]="#8d786f"

# Processes box outline color
theme[proc_box]="#8d786f"

# Box divider lines and small box borders
theme[div_line]="#8d786f"

# Temperature graph colors
theme[temp_start]="#2e4651"
theme[temp_mid]="#344852"
theme[temp_end]="#2e4651"

# CPU graph colors
theme[cpu_start]="#2e4651"
theme[cpu_mid]="#344852"
theme[cpu_end]="#2e4651"

# Mem/Disk free meter
theme[free_start]="#2e4651"
theme[free_mid]="#344852"
theme[free_end]="#2e4651"

# Mem/Disk cached meter
theme[cached_start]="#335666"
theme[cached_mid]="#2e4651"
theme[cached_end]="#344852"

# Mem/Disk available meter
theme[available_start]="#2e4651"
theme[available_mid]="#344852"
theme[available_end]="#2e4651"

# Mem/Disk used meter
theme[used_start]="#2e4651"
theme[used_mid]="#344852"
theme[used_end]="#2e4651"

# Download graph colors
theme[download_start]="#2e4651"
theme[download_mid]="#335666"
theme[download_end]="#344852"

# Upload graph colors
theme[upload_start]="#344852"
theme[upload_mid]="#335666"
theme[upload_end]="#2e4651"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#2e4651"
theme[process_mid]="#2e4651"
theme[process_end]="#344852"